### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by sualeh** [adriens/excuses-sdk#7]
Add tests, which will also serve as example code on how to use the API. 😄

**Comment by adriens** [comment]
Definitley, but can'at wait to implement the IoT, but wait, you gave me an even crazier idea 😆

**Comment by adriens** [comment]
@sualeh : 

![image](https://user-images.githubusercontent.com/5235127/134763402-6461ae96-6382-4d72-b15d-3b8f1f004419.png)
